build:
    tests:
        override:
            -
                command: 'phpunit test --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'