build:
    tests:
        override:
            -
                command: 'php tools/phpunit.phar --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'