build:
    environment:
        php: '7.0.8'
    tests:
        override:
            -
                command: 'php tools/phpunit.phar test --coverage-clover=coverage.xml --whitelist=src'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'