build:
    tests:
        override:
            -
                command: 'php tools/phpunit.phar test --coverage-clover=/tmp/coverage.xml'
                coverage:
                    file: '/tmp/coverage.xml'
                    format: 'php-clover'